photo_album/config/routes.rb
Rails.application.routes.draw do

  resources :photos
  

end

photo_album/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

photo_album/app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :file_location, PhotoImageUploader
	validates_presence_of :title, :date, :description, :file_location
end

photo_album/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

photo_album/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def index
		@photos = Photo.all

	end

	def new 
		@photo = Photo.new

	end

	def create
	 @photo = Photo.new(photo_params)
	 	if @photo.save
			redirect_to photos_url
		else
			render :new
		end

	end

	def show
	 @photo = Photo.find(params[:id])
	end

	def edit
	 @photo = Photo.find(params[:id])
	end

	def update
	 @photo = Photo.find(params[:id])
	 if @photo.update(photo_params)
	 		redirect_to photo_path(@photo)
	 else
	 		render :edit
	 end

	end

	def destroy
	 @photo = Photo.find(params[:id])
	 @photo.destroy

	 redirect_to photos_url
	end

	private

	def photo_params
	 params.require(:photo).permit(:title, :date, :description, :file_location)
	end

end

photo_album/app/helpers/application_helper.rb
module ApplicationHelper
end

photo_album/app/helpers/photos_helper.rb
module PhotosHelper
end

photo_album/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

photo_album/app/views/photos/_form.html.erb
<% if @photo.errors.present?%>

  <p class="errors">We have errors !</p>
  <ul>
        <% @photo.errors.each do |error, message|%>
          <li> <%= "#{error.capitalize}  #{message}" %></li>
        <% end %>
  </ul>
<% end%>
<%= form_for @photo do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title%>

  <%= f.label :date%>
  <%= f.text_field :date%>

  <%= f.label :description%>
  <%= f.text_field :description%>

  <%= f.label :file_location%>
  <%= f.file_field :file_location%>
  
  <%= f.submit %>
<% end %>

photo_album/app/views/photos/edit.html.erb
<%= render :partial => "form" %>

photo_album/app/views/photos/index.html.erb
<ul>
 <% @photos.each do |photo| %>
  <li>
    <%= photo.title %>
    <%= link_to 'Show', photo_path(photo) %>
    <%= link_to 'Edit', edit_photo_path(photo) %>
    <%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %>
  </li>
 <% end %>
</ul>

<%= link_to 'New Photo', new_photo_path %>

photo_album/app/views/photos/new.html.erb
<%= render :partial => "form" %>

photo_album/app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url %>
<%= simple_format(@photo.description) %>

<p><%= link_to 'Back to index', photos_path %></p>